export default function Notifications() {
  return (
    <div className="bg-slate-200">
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
      <p>Notifications</p>
    </div>
  )
}
